import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import AuthProvider from "./store/Provider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";

const inter = Nunito_Sans({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "TinyTrail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ToastContainer />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
